= Agent Traces with MLflow and Red Hat OpenShift AI
:navtitle: Home

== Goal

This course covers how to deploy MLflow, as included with Red Hat OpenShift AI 3.4.
You will learn how to collect traces of an agentic application using the MLflow SDK with Python.
You will also learn how to visualize those traces using the Red Hat OpenShift AI web interface.

You should reserve a full working day to complete this course.

IMPORTANT: Red Hat associates must enroll using the https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering%3D92545261[Red Hat Learning Portal^], and Red Hat Partners must enroll using https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering%3D92545334[Red Hat Partner Connect^] to register this course in their learning history.


== Objectives

On completing this course, you should be able to:

* Understand how MLflow relates to agentic applications and Red Hat OpenShift AI.

* Deploy a development environment with MLflow.

* Collect and visualize traces from agentic applications using MLflow.

== Audience

* Software developers working on agentic applications and agentic harnesses.

* Red Hat and Partner roles that perform demonstrations, proof of concept (PoC) and proof of value (PoV) of MLflow with Red Hat OpenShift AI, such as Solution Architects.

* Red Hat and Partner roles that implement and support MLflow with Red Hat OpenShift AI, such as Services Consultants, Technical Account Managers, and Customer Support Engineers.

== Prerequisites

This course assumes that you have the following experience:

* Familiarity with generative AI and agentic application concepts.

* Familiarity with the basic operation of Red Hat OpenShift AI.

* Python programming skills are recommended but not required because this training provides ready-to-run sample code.

== Classroom environment

The demo catalog entry https://catalog.demo.redhat.com/catalog/babylon-catalog-prod?item=babylon-catalog-prod/published.openshift-ai-v3.prod[Red Hat OpenShift AI 3^] provides a single-node OpenShift cluster (SNO), backed by an AWS instance with a single GPU, with a predeployed `llama-32-3b-instruct` model which is capable of making tool calls.

This course uses that demo entry as-is and, at the time of testing, it provided the following product releases:

* Red Hat OpenShift AI 3.4.2
* Red Hat OpenShift Container Platform 4.20.27

Learners will configure any additional components required by either MLflow itself or any of the course activities, as part of course activities.
A public Git repository contains all sample Python code and Kubernetes manifests required to complete hands-on activities.

== Other sources of information

For documentation about MLflow with Red Hat OpenShift AI, see the https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4[Red Hat OpenShift AI product documentation^].

For upstream MLflow documentation, see the https://mlflow.org/docs/latest/index.html[MLflow project documentation^], especially the section about https://mlflow.org/docs/latest/genai/tracing/[Tracing (Observability)^].

== Author

*Fernando Lozano* +
Training Content Architect +
Red Hat - Product Portfolio Marketing & Learning

_Thanks to Adel Zaalouk, Andy Stoneberg, Calum Murray, Cansu Kavili Oernek, Francisco Arceo, Harshad Reddy Nalla, Jaideep Rao, Lazaro Coronado Torres, Matt Prahl, Peter Double, and Waldirio Pinheiro for their support creating this course and its hands-on activities_.
