= Introduction to MLflow in Red Hat OpenShift AI

Objective::

Understand MLflow's features for agentic applications and its place as part of Red Hat OpenShift AI.

== Introduction to MLflow

According to its own https://mlflow.org/[website^]:

[quote]
____
MLflow is the largest open source AI engineering platform for agents, LLMs, and ML models.
MLflow enables teams of all sizes to debug, evaluate, monitor, and optimize production-quality AI applications while controlling costs and managing access to models and data. 
____

MLflow provides fundamental observability and experiment-tracking capabilities that enable developers and data scientists to ensure their applications work beyond a demonstration and perform as expected in production.

MLflow capabilities support developers and data scientists optimizing their applications for cost and accuracy, for example, as they select smaller models or tune their prompts, so they are confident they did not introduce unacceptable performance degradation.

AI-enabled applications usually degrade over time, because user behavior and input data changes.
MLflow enables continuous evaluation of runtime performance of applications, so improvements can be made before users report problems.

== High-level architecture of MLflow

MLflow is based on a client/server architecture.
A client application, which is instrumented by using either the MLflow SDK or OpenTelemetry, sends observability data, such as metrics and traces, to an MLflow server, which stores that data and provides HTML-based visualization of it.

image::mlflow-arch.svg[title="Architecture of MLflow"]

The application is responsible for interacting with machine learning (ML) models or, in the case of generative AI (gen AI) applications, with large language models (LLMs).
The gen AI application is also responsible for interacting with MCP servers, providing local tools, or connecting to retrieval-augmented generation (RAG) data sources.

It does not matter whether the "application" is a user-facing application, an autonomous agent, or a training or evaluation pipeline.
It just needs to send observability data to an MLflow server.

Client applications can also consume data from MLflow servers, for example, to compare metrics from different training sessions and determine which one provided better outputs, or to track performance degradation, over time, for a production application.

The MLflow server makes use of a relational database and an artifact store to record artifacts such as model weights (in the case of training ML models) or prompts (in the case of gen AI applications).
It is recommended that the artifact store be an S3 service, for scalability.

The relational database stores metadata and tags which enables the MLflow server to relate all inputs, outputs, and observability data from a single training session or from a single conversation with an LLM to each other.
A PostgreSQL database is a popular option for the MLflow database.

== MLflow for Generative AI Applications

MLflow started by supporting ML applications and data scientists, offering features to support model training and tuning.
Like many tools focused on ML, MLflow was initially very Python-centric.

More recently, MLflow added features for supporting generative AI (gen AI) applications and agents.
By that time, MLflow was also offering native SDKs for other programming languages, such as TypeScript and Java.

Nowadays, MLflow also supports the OpenTelemetry standard, which enables applications using any programming language and any kind of infrastructure to submit observability data to an MLflow server.

== MLflow experiments and workspaces

Experiments are a key concept in MLflow.
An _experiment_ is a grouping of observability data from multiple runs.
Each run collects all data obtained while running an AI application once.
Runs can take multiple forms, the ones that pertain to this course are _traces_, which record the interactions between an agent and a model.

A _workspace_ is a grouping of experiments.
Typically, a workspace corresponds to an application, and experiments correspond to running the application with different configuration parameters, such as different models, or different system prompts.

Then, inside an experiment, each run connects an input to its output, and provides metrics and other observability data from that run.
Frequently, there are multiple runs, such as multiple traces, which start from exactly the same input data because LLMs are inherently nondeterministic.

== MLflow Features in Red Hat OpenShift AI

MLflow is a comprehensive platform for managing AI applications; however, it does not provide _everything_ data scientists, software developers, and AI engineers need to develop and manage their ML or gen AI applications.
Providing "everything" is the stated goal of Red Hat OpenShift AI (RHOAI).
While MLflow provides many features that are useful by themselves, others work better when paired with tools outside of MLflow.

Sometimes, there is overlap between a feature from MLflow and a feature from another component of RHOAI, for example, the Model Registry, which in RHOAI comes from Kubeflow.
All features from MLflow are available from RHOAI, but not all of them may be integrated with the RHOAI dashboard and with other features of RHOAI. 

The upstream web interface from MLflow is available unchanged, as a standalone application, from RHOAI.
Users are free to continue using this interface.
However, you may find it easier and more convenient to use the subset of features made available from the RHOAI dashboard, because it facilitates using these features integrated with other components and features from RHOAI.

== What's Next

//Now that you understand MLflow's role in RHOAI and agentic applications, the next section provides a quiz to verify your understanding of key MLflow concepts.

Now that you understand MLflow's role in RHOAI and agentic applications, the next activity walks through the environment for hands-on activities, which provides an instance of RHOAI preconfigured with an LLM.

////
Introduction to MLFlow in Red Hat OpenShift AI
Summary of MLFlow features supported or recommended in an RHOAI instance. Not all of it MLFlow is supported by Red Hat, and some of its functionality is better provided by components of RHOAI other than MLFlow
Focus on MLFlow features for generative AI applications. Mention that MLFlow also offers features for predictive AI and generic machine learning but they are out of scope for this course.
Quick introduction to the concept of experiments in MLFlow and how it applies to agentic application development.
////
