= Lab: Trace MCP Tool Calls from an Agent

Objective::

Deploy an MCP server and capture its tool invocations in MLFlow traces.

WARNING: Work In Progress

== Before you begin

You need access to the predeployed Red Hat OpenShift AI (RHOAI) instance provided in your lab environment, which was already configured by the xref:ch2-deploy-mlflow:s2-deploy-lab.adoc[second lab] with a development instance of the MLFlow server.

Ensure you have:

* Access credentials and the URL for the RHOAI dashboard
* A web browser to access the RHOAI dashboard
* Access credentials and the URL for the OpenShift web console

== Instructions

You will deploy an MCP server, which allow instrospection of the state of an OpenShift cluster and its resources.
Then, you will create a simple agent which uses that MCP server to assess the state of workloads running on your OpenShift cluster.
Finally, you will interpret traces from the agent to assess if it is able to make efficient use of tools from the MCP server.

As you perform this activity, you will alternate between three browser tabs:

* The Red Hat OpenShift web console
* The Red Hat OpenShift AI (RHOAI) dashboard
* A Jupyter notebook from a RHOAI workbench.

Once you open one of these tabs, keep it open because you may return to it later.

1. Deploy the OpenShift MCP server with restricted privileges.

.. TBD

2. Test the MCP server using the Gen AI playground

.. TBD

3. Create a Jupyter notebook for your agentic application.

.. TBD

4. Insert the code for a simple agent into your notebook.

.. TBD

5. Run your agent to verify it is working.

.. TBD

6. Instrument your agent with MLFlow tracing.

.. TBD

7. Run your agent to verify it continue working after changes.

.. TBD

8. View the trace in the RHOAI dashboard.

.. TBD

9. Add sample prompts to the prompt registry.

.. TBD

10. Modify your agent to retrieve its prompts from the prompt registry.

.. TBD

11. Run your agent, to verify it continue working after changes, and view its traces.

.. TBD


1. Deploy an MCP server.

.. Something to do, using a graphical or web UI.
Click menu:Save As[] to save your work.

.. More things to do

2. Add the MCP server to your agentic application.

.. Something to do, using a shell.
+
[source,console,subs="verbatim,quotes"]
--
$ *command --options fixed-arguments _variable-arguments_*
output of the command
highlight *something* in the output
--


.. More things to do.
Press kbd:[Ctrl+C] to interrupt.

Summary of what you accomplished.

== What's next

Congratulations! You've completed this course and learned how to deploy MLFlow, collect traces from agentic applications, and visualize trace data. You can now apply these skills to troubleshoot and improve your own agentic applications.

////
Trace MCP tool calls from an agent
Deploy an MCP server, such as the OpenShift MCP or the Red Hat Search MCP. Any other MCP would do, but let's take the opportunity to feature MCP servers from Red Hat.
Validate the MCP server deployment using the playground.
Add the MCP server to the agentic application.
Inspect runs and traces which include good and bad MCP tool invocations
Maybe move RAG into this lab, or make RAG its own stand-alone lab?
////
