= Lab: Trace MCP Tool Calls from an Agent

Objective::

Deploy an MCP server and capture its tool invocations in MLFlow traces.

WARNING: Pending review.

== Before you begin

You need access to the predeployed Red Hat OpenShift AI (RHOAI) instance provided in your lab environment, which was already configured by the xref:ch2-deploy-mlflow:s2-deploy-lab.adoc[second lab] with a development instance of the MLFlow server and an RHOAI workbench.

Ensure you have:

* Access credentials and the URL for the RHOAI dashboard
* A web browser to access the RHOAI dashboard
* Access credentials and the URL for the OpenShift web console

== Instructions

You will deploy an MCP server which allow instrospection of the state of an OpenShift cluster and its resources.
Then, you will create a simple agent which uses that MCP server to assess the state of workloads running on your OpenShift cluster.
Finally, you will interpret traces from the agent to assess if it is able to make use of tools from the MCP server.

As you perform this activity, you will alternate between three browser tabs:

* The Red Hat OpenShift web console
* The Red Hat OpenShift AI (RHOAI) dashboard
* A Jupyter notebook from a RHOAI workbench.

Once you open one of these tabs, keep it open because you may return to it later.

1. Deploy the https://catalog.redhat.com/en/software/container-stacks/detail/69a94fac9956d5da803edd1a#resources[MCP Server for Red Hat OpenShift^] with restricted privileges, by using its https://github.com/openshift/openshift-mcp-server/blob/main/charts/kubernetes-mcp-server/README.md[helm chart^] and the OpenShift Ecosystem Catalog.

.. Open the OpenShift web console and log in using the `admin` user.
In the left navigation menu, select menu:Ecosystem[Software Catalog].
Scroll down to find the *Type* heading and click menu:Helm charts[].

.. Scroll up to the *All items* field and type `mcp`.
Then click the entry menu:Red Hat OpenShift Mcp Server[] and, on its details pane, click menu:Create[].

.. In the *Create Helm Release* page, click the menu:Project[] field, which probably displays the `default` project, and click menu:Create Project[]. 
Type `mcp-servers` as the *Name* field and click menu:Create[].

.. In the *Create Helm Release* page, delete all contents from its text editor and paste the following configuration, which gives the MCP server read-only access to all resources int the cluster, but disables external access.
+
[source,yaml,subs="verbatim,quotes"]
----
ingress:
  enabled: false
rbac:
  extraClusterRoleBindings:
    - name: use-view-role
      roleRef:
        name: view
        external: true
----

.. Click menu:Create[].
You should be now in the menu:Workloads[Topologu] page of the `mcp-servers` project, which displays a Helm icon for the MCP server deployment.
Click the Helm icon to display its workload details page, to the right, and wait until its only pod is runnig.

2. Test the MCP server using the Gen AI studio

.. Create a config map which provides the Gen AI studio with a list of available MCP servers.
+
In the left navigation pane, select menu:Workloads[ConfigMaps] and, in the menu:Project[] field at the top, select the `redhat-ods-applications` project.

.. Click menu:Create ConfigMap[] and, in the *Create Configmap* page, type `gen-ai-aa-mcp-servers` as the *Name* field.

.. Type the following as the *Value* field and click menu:Create[].
+
[source,json,subs="verbatim,quotes"]
----
{
      "url": "http://redhat-openshift-mcp-server.mcp-servers.svc.cluster.local:8080/mcp",
      "description": "Red Hat OpenShift MCP server"
}
----

.. Verify that the Gen AI studio can connect to the MCP server.
+
Open your RHOAI dashboard and login as the `admin` user.
In the left navigation pane, select menu:Gen AI studio[AI assets endpoints] and select the menu:MCP servers[] tab.
It should list the `OpenShift-MCP-Server`, as configured by the config map, with the `Active` status, which means the Gen AI studio was able to retrieve the tools list from the MCP server.

.. Test the MCP server tools using a playground.
+
In the left navitation pane, select menu:GenAI studio[Playground].
Then type `my` in the *Project* field and select menu:my-first-project[].
Click menu:Create playground[].
In the *Configure playground* form, leve the model checked and click menu:Create[].

.. Wait while the Gen AI studio deploys a llama stack server for your playground.
It displays a confirmation popup when done and enters the *Playground* page, 

.. In the *Configure* pane of the playground, select the menu:MCP[] tab and check the row with name `OpenShift-MCP-Server`.
You should see a popup stating *Connection successful* and the number of tools provided by the MCP server.
Click menu:Save[] to select all tools.

.. In the right pane, click the `Send a message...`​ text and type a prompt which requires using the MCP server, for example:
+
[source,none,subs="verbatim,quotes"]
----
Which pods are in my-first-model?
----

.. Type kbd:[Enter] to submit the prompt.
Hopefully, you will get a correct response, which you can optionally verify by switching to the OpenShit web console and listing pods from the `my-first-model` project.

3. Import the Jupyter notebook for a simple agent.

.. In the left navigation pane, select menu:Projects[] and, in the *Project* field, select menu:All projects[].
Then type `my` and, in the list of projects, select menu:my-first-model[].

.. In the projects page for `my-first-model`, select the menu:Workbenches[] tab.
Click the menu:test-mlflow[] workbench, which you created in the xref:ch2-deploy-mlflow:s2-deploy-lab.adoc[second lab], to open its jupyter lab in a new browser tab.

.. In the left toolbar of your Jupyter Lab, click the menu:Git Clone[] icon.

.. In the *Clone a repo* popup, type `https://github.com/RedHatQuickCourses/rhoai-mlflow-samples.git` as the URI of the remote Git repository and click menu:Clone[].

.. In the file browser of your Jupyter Lab, enter the `/rhoai-mlflow-samples/traces` directory and then open the `basic-agent.ipnyb` notebook.

4. Review the code for a simple agent.
+
NOTE: The expanations here are *not* intended to explain all code in the agentic application, but just its general structure, so you can later read its traces.
The code snippets here enable learners to locate each section of code, if they wish to study and use it as a starting point for their agentic applications.

.. In its first cell, notice the use of `--extra-index-url` option for the `pip install` command.
It is necessary because the RHOAI index does not include the `openai-agents` library.
That way, pip falls back to the comunity index for any module not present in its primary index. 
+
[source,python,subs="verbatim,quotes"]
----
! pip install --extra-index-url https://pypi.org/simple openai openai-agents mlflow[kubernetes]
----

.. In the second cell, notice the variables which set the URLs and connection parameters for the model server, the MCP server, and the MLFlow server.
They are all internal URLs, which refer to their respective Kubernetes services.
+
[source,python,subs="verbatim,quotes"]
----
BASE_URL = "http://llama-32-3b-instruct-predictor.my-first-model.svc.cluster.local:8080/v1"
model_name = "llama-32-3b-instruct"

MCP_SERVER_URL = "http://redhat-openshift-mcp-server.mcp-servers.svc.cluster.local:8080/mcp"

MLFLOW_TRACKING_URL = "https://mlflow.redhat-ods-applications.svc.cluster.local:8443"
MLFLOW_EXPERIMENT = "basic-agent"
----

.. Then it sets a user prompt, which should require the MCP server, and a generic system prompt.
+
[source,python,subs="verbatim,quotes"]
----
input_text = """
List the names of all pods in namespace 'my-first-model'
"""
system_instructions = """
You are a helpful AI assistant.
You are designed to answer questions in a concise and professional manner.
"""
----

.. So far, the code is very similar from previous examples but, after it gets the service account token and eneables MLFlow tracing, the code to connect to the model and submit a prompt is _very_ different from the previous chat example.
+
Differences start by creating an asynchronous client for the model server: 
+
[source,python,subs="verbatim,quotes"]
----
async def main():
    """Main async function to run chat with MCP tools"""

    # Configure custom OpenAI endpoint globally
    custom_client = AsyncOpenAI(
        base_url=BASE_URL,
        api_key=AUTH_TOKEN
    )
----

.. It also creates an asynchronous MCP client:
+
[source,python,subs="verbatim,quotes"]
----
    async with MCPServerStreamableHttp(
        name="Remote MCP Server",
        params={
            "url": MCP_SERVER_URL,
            "timeout": 30,
        },
        cache_tools_list=True,
    ) as mcp_server:
----

.. The agent object refers, implicitly, to the global OpenAI endpoint configured earlier, and also refers explicitly to the MCP client and the system prompt.
+
[source,python,subs="verbatim,quotes"]
----
        agent = Agent(
            name="Assistant",
            instructions=system_instructions,
            model=model_name,
            mcp_servers=[mcp_server],
        )
----

.. An asynchronous runner submits the prompt to the agent and displays its final response.
+
The agent loops on the responses received from the model, invoking MCP tools, and sending the output of tool calls back to the model.
+
This loop, inside the agent object, continues until the agent gets a response from the model which does *not* request another tool call.
+
[source,python,subs="verbatim,quotes"]
----
        # Run the agent
        result = await Runner.run(agent, input_text)

        # Print the final output
        print("Assistant:", result.final_output)
----

.. The final piece of code enables running the asyncronous code from both a standalone application and a Jupyter notebook, which already sets an asynchronous runner for its cells.
+
[source,python,subs="verbatim,quotes"]
----
        try:
            get_ipython()
            # Running in Jupyter - use await directly (top-level await is supported)
            import nest_asyncio
            nest_asyncio.apply()
            asyncio.run(main())
        except NameError:
            # Not in Jupyter - use asyncio.run() normally
            asyncio.run(main())
----

5. Run the agent to produce a trace.

.. In the top toolbar from the notebook, click the menu:fast forward[] icon, with the tooltip menu:Restart the kernel and run all cells[].

.. It may take a while to download all OpenAI and MLFlow libraries and their dependencies, in the first cell before it actually submits the prompt, in the second cell.
+
If all goes well, you will get a correct response, similar to the following example:
+
[source,python,subs="verbatim,quotes"]
----
Connecting to MCP server at http://redhat-openshift-mcp-server.mcp-servers.svc.cluster.local:8080/mcp...

Found 14 tools from MCP server:

Processing query: List the names of all pods in namespace 'my-first-model'

Assistant: Based on the output, the names of all pods in the namespace 'my-first-model' are:

1. llama-32-3b-instruct-predictor-6bd8fbdd49-28b9m
2. llama-32-3b-instruct-predictor-6bd8fbdd49-j9dxk
3. llama-32-3b-instruct-predictor-6bd8fbdd49-nkvn9
4. llama-32-3b-instruct-predictor-6bd8fbdd49-vvwgb
5. llama-32-3b-instruct-predictor-6bd8fbdd49-wbgxn
6. lsd-genai-playground-55555b9d99-78zqk
7. test-mlflow-0
----
+
The output includes the number of tools from the MCP server as proof that the agent can connect to it, even if the response looks like it didn't.
+
NOTE: There is a higher change of getting an incorrect response, or no reponse at all, compared to the previos example.
The later may happen because the agent received too many tool call requests from the model, and decided that the model is lost and cannot produce a final response.

6. View the trace in the RHOAI dashboard.

.. Switch to the RHOAI dashboard and, in the left navigation pane, select menu:Develop & train[Experiments (MLflow)].
In the menu:Project[] field, type `my` and select the menu:my-first-model[] project.
Then click the menu:basic-agent[] experiment.

.. In the left pane of the *Experiments* page for the `basic-agent` project, click menu:Traces[].
You should see a trace whose request and reponse correspond to your notebook run.
Click it.

.. In the summary page for the trace, you will see a number of items labeled menu:AsyncCompletions[].
Each of them corresponds to a roundtrip between the agent and the model.
If you are lucky, you will see two of them.

.. Click the menu:expand/collapse[] icon (menu:>[]) from the first menu:AsyncCompletions[], but do *not* click the menu:AsyncCompletions[] itself.
You will see it contains menu:Inputs[] and menu:Outputs[].
+
The menu:Inputs[] include the user and system prompts, a list of tools, and a number of OpenAI parameters which the sample agent didn't set explicitily, so they took their default values.
+
The menu:Outputs:[] include a reques to call the tool named `pods_lists_in_namespace` with arguments `"namespace": "my-first-model"`

.. Click the menu:expand/collapse[] icon (menu:>[]) from the second (or latest) menu:AsyncCompletions[].
+
Notice its menu:Inputs[] include everythig you saw from the previous completions in the same trace, including prompts and lists of tools. But it adds the results of the tool call requested by the previous completion.
+
It may be hard to read in the trace, but you can recognise similarities with the output of an `oc get pod -o wide` command.
+
The menu:Outputs[] should match the final response displayed by your notebook run.

.. If you got more than two menu:AsyncCompletions[] items, it might be because the model was not able to recognize that the tool call contains the information it needs, and requested a another tool call, maybe with different parameters, maybe of a different tool.
+
For more complex prompts, it might be necessary to use the output of a tool call as parameters of another tool call, and many such rounds might be necessary.
But you may find that, even with simpler prompts, a model might requests tool calls which make no sense. 

.. When you are satisfied that you understand the trace, click the its menu:close[] icon, that is, the menu:x[] to the top right of the trace summary page, to return to the list of traces.

7. (Optional) You may switch to your Jupyter Lab and run the second cell again a few times.
Each run produces its own trace, and they may take different numbers of completions to produce its response.

.. Sometimes the responses will be correct, as in including the sames of all pods and no extra pods, but vary on their wording.

.. Sometimes you may get an incorrect response, such as `This output indicates that there are no pods in the 'my-first-model' project.`

.. Because the demo enviroment only supports a small model, with a small context window, you can easily devise a prompt which produces an error, such as lising all pods in the cluster.
But you can also find that there are a number of useful prompts this small model can answer correctly and frequently.

.. You may also try subtle changes in the prompts, for example referring to "the my-first-model project" instead of to a "namespace", or trying to provide a better suited system prompt for an IT operations or a Kubernetes administrator persona.

////

7. Add sample prompts to the prompt registry.

.. TBD

8. Modify your agent to retrieve its prompts from the prompt registry.

.. TBD

9. Run your agent, to verify it continue working after changes, and view its traces.

.. TBD
////

After completing these steps, you have executed a simple agentic application which produces traces on the MLFlow server in RHOAI.
You also interpreted those traces to identify when the model requested tool calls, the specific data returned by the MCP server for each call, and how the data was send back from the agent to the model.
Finally, you verified that the non-deterministic nature of large language models (LLMs) impacts their ability of requesting tool calls and using the returned data to produce a response.

== What's next

Congratulations! You've completed this course and learned how to deploy MLFlow, collect traces from agentic applications, and visualize trace data. You can now apply these skills to troubleshoot and improve your own agentic applications.

////
Trace MCP tool calls from an agent
Deploy an MCP server, such as the OpenShift MCP or the Red Hat Search MCP. Any other MCP would do, but let's take the opportunity to feature MCP servers from Red Hat.
Validate the MCP server deployment using the playground.
Add the MCP server to the agentic application.
Inspect runs and traces which include good and bad MCP tool invocations
Maybe move RAG into this lab, or make RAG its own stand-alone lab?
////
