= Lab: Deploy MLflow on Red Hat OpenShift AI

Objective::

Deploy and verify a development instance of MLflow in Red Hat OpenShift AI.

== Before you begin

You need access to the predeployed Red Hat OpenShift AI (RHOAI) instance provided in your lab environment. Ensure you have:

* Access credentials for the RHOAI dashboard
* A web browser to access the RHOAI dashboard
* Access credentials for the OpenShift web console

== Instructions

You will enable MLflow on your Data Science Cluster singleton resource and deploy a development instance of the MLflow server.
Then you will create a Jupyter notebook to test connectivity to the MLflow server.
You will use the MLflow SDK for Python.

As you perform this activity, you will alternate between three browser tabs:

* The Red Hat OpenShift web console
* The Red Hat OpenShift AI (RHOAI) dashboard
* A Jupyter notebook from a RHOAI workbench.

Once you open one of these tabs, keep it open because you may return to it later.

=== Install and configure the MLflow Server

1. Enable MLflow on RHOAI by editing its data science cluster resource.

.. Open the OpenShift web console and log in as a user with `cluster-admin` rights.

.. In the left navigation pane, select menu:Ecosystem[Installed Operators].
Then click menu:Red Hat OpenShift AI[].

.. In the Red Hat OpenShift AI operator page, select the menu:Data Science Cluster[] tab.
Then click the menu:default-dsc[] resource.

.. In the `default-dsc` resource page, select the menu:YAML[] tab.
In the text editor, search for the `spec.components` field, and set `mlflowoperator.managementState` to `Managed`.
+
[source,yaml,subs="verbatim,quotes"]
----
...
spec:
  components:
    *mlflowoperator:*
      *managementState: Managed*
    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headless
...
----

.. Click menu:Save[] and wait until you see a confirmation message similar to:
+
[source,none,subs="verbatim,quotes"]
----
alert:default-dsc has been updated to version 1186240
----

.. If you receive an error message, fix the errors in your YAML and try saving again.

.. Alternatively, you could run the following `oc patch` command, which is provided by the https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html/working_with_mlflow/installing-mlflow_mlflow#mlflow-configuration-parameters_mlflow[Red Hat OpenShift AI product documentation^]:
+
[source,console,subs="verbatim,quotes"]
----
$ *oc patch datasciencecluster default-dsc --type=merge \
-p '{"spec":{"components":{"mlflowoperator":{"managementState":"Managed"}}}}'*
datasciencecluster.datasciencecluster.opendatahub.io/default-dsc patched
----

2. Configure your MLflow instance by creating an MLflow resource.

.. In the left navigation pane, select menu:Home[API Explorer].
Then enter `MLflow` in the search field.
You will see three resource types; click menu:MLflow[].

.. In the MLflow Resource details page, select the menu:Instances[] tab and click menu:Create MLflow[].

.. In the YAML text editor, delete all of its sample contents and enter the following, which corresponds to the example from https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html/working_with_mlflow/installing-mlflow_mlflow#mlflow-configuration-parameters_mlflow[Minimal development or test deployment^] in the Red Hat OpenShift AI product documentation.
+
[source,yaml,subs="verbatim,quotes"]
----
apiVersion: mlflow.opendatahub.io/v1
kind: MLflow
metadata:
  name: mlflow
  namespace: redhat-ods-applications
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  backendStoreUri: "sqlite:////mlflow/mlflow.db"
  artifactsDestination: "file:///mlflow/artifacts"
  serveArtifacts: true
----

.. Click menu:Create[] and, in the MLflow details page, wait until the `Available` condition is `True` and the `Progressing` condition is `False`.

=== Test your MLflow server using the dashboard and a workbench

3. Verify MLflow is available from RHOAI and create an empty experiment.

.. Open your RHOAI dashboard.
If it is already open, refresh your browser window.

.. In the left navigation pane, expand menu:Develop & train[].
Notice the new item named menu:Experiments (mlflow)[] and click it.

.. In the menu:Project[] field, select the menu:my-first-model[] project.

.. Click menu:Create Experiment[] and enter `dummy experiment` as its name.

.. Verify that you see the Experiments page for `dummy experiment` but there is no data on any of its pages, such as menu:Traces[], menu:Sessions[], or menu:Prompts[].

.. Creating an empty experiment is sufficient to prove that your MLflow instance can connect to its database and artifacts storage.

.. You can, alternatively, open the upstream MLflow web interface by clicking the menu:applications[] menu, near the top right of the navigation bar close to the help icon, and selecting menu:MLflow[].
You should not need it: all functionality you need for this course is available from the RHOAI dashboard.

4. Test connectivity to MLflow from a Jupyter notebook inside a workbench.
+
NOTE: If you have trouble typing the Python code in this and other activities of this course, or you cannot cut-and-paste from the course page, you can access the complete source code for all Jupyter notebooks in a https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/tree/main/traces[git repository^].

.. In the left navigation pane, click menu:Projects[] and select menu:All projects[] in the menu:Project[] field.
Then enter `my` in the *Filter by name* field and click menu:my-first-model[] in the list of projects.

.. In the Projects page for `my-first-model`, select the menu:Workbenches[] tab and click menu:Create workbench[].

.. In the Create workbench page, enter `test-mlflow` for the *Name* field and, in the *Workbench image* field, select menu:Jupyter | Minimal | CPU[].

.. Leave all other fields with their default values and click menu:Create workbench[].

.. In the Workbenches list, wait until the row for the `test-mlflow` workbench displays a `Ready` state and then click menu:test-mlflow[] to open its Jupyter Lab in a new browser tab.

.. Click the menu:Python 3.12[] Notebook icon to create an empty notebook.

.. In the first cell, enter:
+
[source,python,subs="verbatim,quotes"]
----
! pip install mlflow[kubernetes]
----

.. In the top toolbar from the notebook, click the menu:play[] icon, having the tooltip "Run this cell and advance".

.. Wait until the MLflow SDK and all its dependencies are loaded from the RHOAI index into the workbench.

.. After the `pip` command finishes, enter the following on the second cell of your notebook:
+
[source,python,subs="verbatim,quotes"]
----
import os
import mlflow

os.environ["MLFLOW_TRACKING_AUTH"]="kubernetes-namespaced"
mlflow.set_tracking_uri("CHANGE_ME")

print(mlflow.list_workspaces())
----

.. Switch to your RHOAI dashboard page, which should still be in the Experiments page.
Notice, near the top left, the menu:Launch MLflow[] link.
Right-click it and copy its URL to your clipboard.

.. Switch to your Jupyter Lab browser tab and, in the second notebook cell, replace the `CHANGE_ME` text with the URL on your clipboard.
+
[NOTE]
====
In this example, we are using the _external_ URL of the MLflow server, which depends on the applications domain of your OpenShift Ingress operator.
This is the URL you would use for applications running outside of its OpenShift cluster.

External applications also need to set the `MLFLOW_TRACKING_TOKEN` environment variable with a valid OpenShift authentication token, for example the one returned by the `oc whoami -t` command.
====

.. In the top toolbar from the notebook, click the menu:play[] icon.
The results should be an array containing a single `Workspace` object named `my-first-model`.
+
This notebook takes advantage of the integration between the RHOAI dashboard and its managed instance of the MLflow server.
It connects using the service account of the `test-mlflow` workbench, which is authorized to access the MLflow workspace corresponding to its `my-first-model` project.

.. If you wish, you can remove the unnamed notebook, or if you prefer you can save it, rename it to `test.ipynb`, and reuse it for the next activity.
Whatever your preference, do NOT delete the `test-mlflow` workbench because you will keep using it in the next activity.

=== Summary

After completing these steps, you have verified that you have a minimal but functional MLflow instance, to which you can connect from applications running inside your RHOAI cluster and store data from your experiments.

== What's next

Now that you have a working MLflow deployment, the next chapter explores how to collect traces from agentic applications using the MLflow SDK.

////
Deploy MLFlow on Red Hat OpenShift AI for development
Quick exploration of the provided demo environment: enabled RHOAI features and predeployed projects and models
Sanity check using either a playground or a workbench
Edit the DSC resource to enable MLFlow
Configure MLFlow with a local SQL lite database and  file-based storage using a PVC and the default storage class.
Verify the healthy of the MLFlow server deployment
Create an experiment using the RHOAI web UI to prove that the MLFlow server is functional
////
