= Lab Environment

== Instructions to Launch Your Lab on the Red Hat Demo Platform (RHDP)

. Log in to the xref:#RHDP-Portal-Links[RHDP portal]
. Search for the catalog entry: `Red Hat OpenShift AI 3`
. Click the catalog entry in the search results.
. On the catalog page, click menu:Order[].
. Enter the required details in the order form and accept the defaults for other fields.
You can use the smaller AWS instance type.
. Review the warning at the bottom of the form and select: +
menu:I confirm that I understand the above warnings[].
. Await the email notification stating that your demo environment is ready and providing its access credentials and URLs.

=== Important Notes:
- This lab may take approximately *90* minutes or more to become ready.
- You can also retrieve access information directly from the RHDP portal.
- This lab uses GPU-enabled instances on AWS, which are in short supply.
It may require multiple attempts to provision or restart. 

[WARNING]
====
Do *not* follow the instructions or showroom from the demo catalog entry.
This course reuses that demo environment but does not require that you perform any of its original activities.

You will use the preprovisioned instance of Red Hat OpenShift AI as-is, and deploy MLflow and sample agentic applications as part of this course activities.
====

=== How to Access Your Lab via the RHDP Portal:
. On the RHDP portal, click menu:Services[] option in the left-hand menu.
. Select your lab from the services listings on the right-hand side of the page to view access details.

[[RHDP-Portal-Links]]
=== RHDP Portal Links
- Red Hat associates: https://demo.redhat.com/[https://demo.redhat.com/^]
- Red Hat partners: https://partner.demo.redhat.com/[https://partner.demo.redhat.com/^]

